import Diaper from "@/app/(trackers)/diaper";
import { render, screen, userEvent, act } from "@testing-library/react-native";
import { Alert } from "react-native";
import { getActiveChildId } from "@/library/utils";
import supabase from "@/library/supabase-client";
import { router } from "expo-router";
import { encryptData } from "@/library/crypto";
import DiaperModule from "@/components/diaper-module";

jest.mock("@/library/supabase-client", () => {
    const insert = jest.fn(async () => ({ error: false }));
    return ({
        from: () => ({
            insert: insert,
        })
    });
});

jest.mock("@/library/crypto", () => ({
    encryptData: jest.fn(async (string) => `Encrypted: ${string}`)
}));

jest.mock("expo-router", () => {
    const replace = jest.fn();
    return ({
        router: {
            replace: replace,
        },
    });
});

jest.mock("react-native", () => {
    const module = jest.requireActual("react-native");
    module.Alert.alert = jest.fn();
    return module;
});

jest.mock("@/library/utils", () => {
    const getActiveChildId = jest.fn(async () => ({ success: true }));
    return {
        getActiveChildId: getActiveChildId
    };
});

jest.mock("@/components/diaper-module.tsx", () => {
    const View = jest.requireActual("react-native").View;
    const DiaperModuleMock = jest.fn(({testID}: {testID?: string}) => (<View testID={testID}></View>));
    return DiaperModuleMock;
});

/*
 *  setDiaperInputs:
 *      Reads update handlers from first call to DiaperModule mock
 *      Calls update handlers with provided inputs
*/
async function setDiaperInputs({
    consistency,
    amount,
    time,
} : {
    consistency?: any;
    amount?: any;
    time?: Date;
}) {
    // read parameters to first call of DiaperModule
    const {
        onConsistencyUpdate,
        onAmountUpdate,
        onTimeUpdate,
    } = (DiaperModule as jest.Mock).mock.calls[0][0];

    if (consistency != null) {
        await act(() => onConsistencyUpdate?.(consistency));
    }
    if (amount != null) {
        await act(() => onAmountUpdate?.(amount));
    }
    if (time != null) {
        await act(() => onTimeUpdate?.(time));
    }
}


describe("Track diaper screen", () => {

    beforeEach(() => {
        // to clear the .mock.calls array
        (Alert.alert as jest.Mock).mockClear();
        jest.spyOn(console, "error").mockClear();
        (DiaperModule as jest.Mock).mockClear();
        (supabase.from("").insert as jest.Mock).mockClear();
        (router.replace as jest.Mock).mockClear();
    });

    test("Renders diaper tracking inputs", () => {
        render(<Diaper/>);

        expect(screen.getByTestId("diaper-main-inputs")).toBeTruthy();
        expect(screen.getByTestId("diaper-note-entry")).toBeTruthy();
    });
    
    test("Renders form control buttons", () => {
        render(<Diaper/>);

        expect(screen.getByTestId("diaper-save-log-button")).toBeTruthy();
        expect(screen.getByTestId("diaper-reset-form-button")).toBeTruthy();
    });
    
    test("Refreshes on reset", async () => {
        const testNote = "test note";
        render(<Diaper/>);

        // write something in the note entry...
        await userEvent.type(
            screen.getByTestId("diaper-note-entry"),
            testNote
        );
        expect(screen.getByDisplayValue(testNote)).toBeTruthy();  // ensure the typed note can be found

        const mainInputs = screen.getByTestId("diaper-main-inputs");  // get the displayed <DiaperModule/>

        await userEvent.press(
            screen.getByTestId("diaper-reset-form-button")
        );

        // ensure note is no longer present
        expect(() => screen.getByDisplayValue(testNote)).toThrow();
        // ensure new instance of <DiaperModule/> is being used
        expect(screen.getByTestId("diaper-main-inputs") === mainInputs).toBeFalsy();
    });
    
    test("Catch unfilled inputs", async () => {
        render(<Diaper/>);

        await userEvent.press(
            screen.getByTestId("diaper-save-log-button")
        );

        // error message generated by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        // Alert.alert() called by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Missing Information`);
        expect((Alert.alert as jest.Mock).mock.calls[0][1])
            .toBe(`Failed to save the Diaper log. You are missing the following fields: consistency and amount.`);

        // repeat with consistency filled
        setDiaperInputs({ consistency: "wet"});  // fill in consistency input
        await userEvent.press(
            screen.getByTestId("diaper-save-log-button")
        );

        // error message generated by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        // Alert.alert() called by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[1][0]).toBe(`Missing Information`);
        expect((Alert.alert as jest.Mock).mock.calls[1][1])
            .toBe(`Failed to save the Diaper log. You are missing the following fields: amount.`);

        // repeat with amount filled
        setDiaperInputs({ consistency: "", amount: "SM"});  // fill in amount input, clear consistency
        await userEvent.press(
            screen.getByTestId("diaper-save-log-button")
        );

        // error message generated by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        // Alert.alert() called by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[2][0]).toBe(`Missing Information`);
        expect((Alert.alert as jest.Mock).mock.calls[2][1])
            .toBe(`Failed to save the Diaper log. You are missing the following fields: consistency.`);
    });
    
    test("Catch getActiveChildId error", async () => {
        const testErrorMessage = "testErrorGetID";

        // library/utils.ts -> getActiveChildId() should be mocked to return:
        // { success: /* falsy value */, error: /* string */ }
        // This should cause error handling in app/(trackers)/diaper.tsx -> saveDiaperLog()
        (getActiveChildId as jest.Mock).mockImplementationOnce(
            async () => ({ success: false, error: testErrorMessage })
        );
    
        render(<Diaper/>);
        setDiaperInputs({ consistency: "wet", amount: "SM"});  // fill in minimum required inputs

        await userEvent.press(
            screen.getByTestId("diaper-save-log-button")
        );

        // error message generated by library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/diaper.tsx -> saveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Error: ${testErrorMessage}`);

        // error message generated by library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[1][0]).toBe(`Failed to save diaper log: ${testErrorMessage}`);
    });
            
    test("Catch ecryption error", async () => {
        const testErrorMessage = "testErrorEncryption";

        // library/crypto.ts -> encryptData() should be mocked to throw an error
        // This should cause error handling in app/(trackers)/diaper.tsx -> createDiaperLog()
        (encryptData as jest.Mock).mockImplementationOnce(
            async () => { throw new Error(testErrorMessage); }
        );

        jest.spyOn(console, "error").mockImplementation(() => null);  // suppress console warnings from within the tested code
    
        render(<Diaper/>);
        setDiaperInputs({ consistency: "wet", amount: "SM"});  // fill in minimum required inputs

        await userEvent.press(
            screen.getByTestId("diaper-save-log-button")
        );

        // error message generated by library/crypto.ts -> encryptData()
        // console.error() called by app/(trackers)/diaper.tsx -> createDiaperLog()
        expect((console.error as jest.Mock).mock.calls[0][0]).toBe(`❌ Encryption or insert failed:`);
        // loose inequality to compare separate Error instances
        expect((console.error as jest.Mock).mock.calls[0][1]).toEqual(new Error(testErrorMessage));

        // Alert.alert() called by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Failed to save diaper log: Encryption or database error`);
    });

    test("Catch supabase insert error", async () => {
        const testErrorMessage = "testErrorInsert";

        // supabase.from().insert() should be mocked to return:
        // { error: /* truthy value */ }
        // This should cause error handling in app/(trackers)/diaper.tsx -> createDiaperLog()
        (supabase.from("").insert as jest.Mock).mockReturnValueOnce(
            { error: testErrorMessage }
        );

        jest.spyOn(console, "error").mockImplementation(() => null);  // suppress console warnings from within the tested code

        render(<Diaper/>);
        setDiaperInputs({ consistency: "wet", amount: "SM"});  // fill in minimum required inputs
        await userEvent.press(
            screen.getByTestId("diaper-save-log-button")
        );

        // error message generated by supabase.from().insert()
        // console.error() called by app/(trackers)/diaper.tsx -> createDiaperLog()
        expect((console.error as jest.Mock).mock.calls[0][0]).toBe(`Error creating diaper log:`);
        expect((console.error as jest.Mock).mock.calls[0][1]).toBe(testErrorMessage);

        // error message generated by supabase.from().insert()
        // Alert.alert() called by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Failed to save diaper log: ${testErrorMessage}`);
    });

    test("Redirects user on successful submit", async () => {
        render(<Diaper/>);
        setDiaperInputs({ consistency: "wet", amount: "SM"});  // fill in minimum required inputs

        await userEvent.press(
            screen.getByTestId("diaper-save-log-button")
        );

        // confirm that the expo-router was called to send the user back to the tracker page
        expect((router.replace as jest.Mock)).toHaveBeenLastCalledWith("/(tabs)");
        expect((router.replace as jest.Mock)).toHaveBeenCalledTimes(1);

        // Alert.alert() called by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Diaper log saved successfully!`);
    });
        
    test("Saves correct values", async () => {
        const testNote = "test note";
        const testTime = new Date;
        const testID = "test ID";

        // mock library/utils.ts -> getActiveChildId() to return the test child ID
        (getActiveChildId as jest.Mock).mockImplementationOnce(
            async () => ({ success: true, childId: testID })
        );

        render(<Diaper/>);
        setDiaperInputs({ consistency: "mixed", amount: "LG", time: testTime });  // fill in minimum required inputs

        // write a note
        await userEvent.type(
            screen.getByTestId("diaper-note-entry"),
            testNote
        );

        // submit log
        await userEvent.press(
            screen.getByTestId("diaper-save-log-button")
        );

        const insertedObject = (supabase.from("").insert as jest.Mock).mock.calls[0][0][0];

        // Ensure supabase.from().insert() was called with the correct values; the note should now be encrypted
        expect(insertedObject.child_id).toBe(testID);
        expect(insertedObject.change_time).toBe(testTime.toISOString());
        expect(insertedObject.note).toBe(await encryptData(testNote));

        // Ensure that log was saved successfully
        // Alert.alert() called by app/(trackers)/diaper.tsx -> handleSaveDiaperLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Diaper log saved successfully!`);
    });

});
