import Nursing from "@/app/(trackers)/nursing";
import { getActiveChildId } from "@/library/utils";
import { render, screen, userEvent } from "@testing-library/react-native";
import { Alert } from "react-native";
import supabase from "@/library/supabase-client";
import { router } from "expo-router";


jest.mock("@/library/supabase-client", () => {
    const insert = jest.fn();
    return {
        from: () => ({
            insert: insert
        })
    };
});

jest.mock("@/library/crypto", () =>({
    encryptData: async () => ""
}));

jest.mock("expo-router", () => {
    const replace = jest.fn();
    return {
        router: {
            replace: replace,
        },
    };
});

jest.mock("react-native", () => {
    const module = jest.requireActual("react-native");
    module.Alert.alert = jest.fn();
    return module;
});

jest.mock("@/library/utils", () => {
    const getActiveChildId = jest.fn();
    return {
        getActiveChildId: getActiveChildId
    };
});


describe("Track nursing screen", () => {
    beforeEach(() => {
        // to clear the .mock.calls array
        (Alert.alert as jest.Mock).mockClear();
    });

    test("Renders nursing tracking inputs", () => {
        render(<Nursing/>);

        expect(screen.getByTestId("nursing-stopwatch")).toBeTruthy();
        expect(screen.getByTestId("nursing-left-amount")).toBeTruthy();
        expect(screen.getByTestId("nursing-right-amount")).toBeTruthy();
        expect(screen.getByTestId("nursing-note")).toBeTruthy();
    });
        
    test("Renders nursing form control buttons", () => {
        render(<Nursing/>);

        expect(screen.getByTestId("nursing-save-log-button")).toBeTruthy();
        expect(screen.getByTestId("nursing-reset-form-button")).toBeTruthy();
    });

    test("Catch no input", async () => {
        render(<Nursing/>);
        await userEvent.press(
            screen.getByTestId("nursing-save-log-button")
        );

        // error message generated by app/(trackers)/nursing.tsx -> handleSaveNursingLog()
        // Alert.alert() called by app/(trackers)/nursing.tsx -> handleSaveNursingLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Please provide at least one side duration or amount`);
    });

    test("Catch getActiveChildId() error", async () => {
        const testErrorMessage = "testErrorInsert";

        // library/utils.ts -> getActiveChildId() should be mocked to return:
        // { success: /* falsy value */, error: /* string */ }
        // This should cause error handling in app/(trackers)/nursing.tsx -> saveNursingLog()
        (getActiveChildId as jest.Mock).mockImplementation(
            async () => ({ success: false, error: testErrorMessage })
        );

        render(<Nursing/>);

        await userEvent.type(
            screen.getByTestId("nursing-left-amount"),
            "0"
        );
        await userEvent.press(
            screen.getByTestId("nursing-save-log-button")
        );

        // error message generated by library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/nursing.tsx -> saveNursingLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Error: ${testErrorMessage}`);

        // error message generated by library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/nursing.tsx -> handleSaveNursingLog()
        expect((Alert.alert as jest.Mock).mock.calls[1][0]).toBe(`Failed to save nursing log: ${testErrorMessage}`);
    });

    test("Catch supabase error", async () => {
        const testErrorMessage = "testErrorInsert";

        // library/utils.ts -> getActiveChildId() should be mocked to return:
        // { success: /* truthy value */ }
        // This should not cause any errors
        (getActiveChildId as jest.Mock).mockImplementation(
            async () => ({ success: true })
        );

        // supabase.from().insert() should be mocked to return:
        // { error: /* truthy value */ }
        // This should cause error handling in app/(trackers)/nursing.tsx -> createNursingLog()
        (supabase.from("").insert as jest.Mock).mockReturnValueOnce(
            { error: testErrorMessage }
        );

        jest.spyOn(console, "error").mockImplementation(() => null);  // suppress console warnings from within the tested code

        render(<Nursing/>);

        await userEvent.type(
            screen.getByTestId("nursing-left-amount"),
            "0"
        );
        await userEvent.press(
            screen.getByTestId("nursing-save-log-button")
        );

        // error message generated by supabase.from().insert()
        // console.error() called by app/(trackers)/nursing.tsx -> createNursingLog()
        expect((console.error as jest.Mock).mock.calls[0][0]).toBe(`Error creating nursing log:`);
        expect((console.error as jest.Mock).mock.calls[0][1]).toBe(testErrorMessage);

        // error message generated by library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/nursing.tsx -> handleSaveNursingLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Failed to save nursing log: ${testErrorMessage}`);
    });

    test("Catch supabase error", async () => {

        // library/utils.ts -> getActiveChildId() should be mocked to return:
        // { success: /* truthy value */ }
        // This should not cause any errors
        (getActiveChildId as jest.Mock).mockImplementation(
            async () => ({ success: true })
        );

        // supabase.from().insert() should be mocked to return:
        // { error: /* falsy value */ }
        // This should cause error handling in app/(trackers)/nursing.tsx -> createNursingLog()
        (supabase.from("").insert as jest.Mock).mockReturnValueOnce(
            { error: false }
        );

        //jest.spyOn(console, "error").mockImplementation(() => null);  // suppress console warnings from within the tested code

        render(<Nursing/>);

        await userEvent.type(
            screen.getByTestId("nursing-left-amount"),
            "0"
        );
        await userEvent.press(
            screen.getByTestId("nursing-save-log-button")
        );

        // confirm that the expo-router was called to send the user back to the tracker page
        expect((router.replace as jest.Mock)).toHaveBeenLastCalledWith("/(tabs)");
        expect((router.replace as jest.Mock)).toHaveBeenCalledTimes(1);

        // Alert.alert() called by app/(trackers)/nursing.tsx -> handleSaveNursingLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Nursing log saved successfully!`);
    });

});
