import { render, screen, userEvent, act } from "@testing-library/react-native";
import Sleep from "@/app/(trackers)/sleep";
import { Alert } from "react-native";
import { router } from "expo-router";
import Stopwatch from "@/components/stopwatch";
import ManualEntry from "@/components/sleep-manual-entry";
import { field, saveLog } from "@/library/log-functions";


jest.mock("expo-router", () => ({
    router: {
        dismissTo: jest.fn(),
    },
}));

jest.mock("react-native", () => {
    const module = jest.requireActual("react-native");
    module.Alert.alert = jest.fn();
    return module;
});

jest.mock("@/components/stopwatch.tsx", () => {
    const View = jest.requireActual("react-native").View;
    const SleepStopwatchMock = jest.fn(({testID}: {testID?: string}) => (<View testID={testID}></View>));
    return SleepStopwatchMock;
});

jest.mock("@/components/sleep-manual-entry.tsx", () => {
    const View = jest.requireActual("react-native").View;
    const ManualInputsMock = jest.fn(({testID}: {testID?: string}) => (<View testID={testID}></View>));
    return ManualInputsMock;
});

jest.mock("@/library/auth-provider", () => ({
    useAuth: () => ({ isGuest: false }),
}));

jest.mock("@/library/log-functions", () => ({
    saveLog: jest.fn(async () => ({ success: true })),
    formatStringList: jest.fn(),
}));


/*
 *  setSleepInputs:
 *      Reads update handlers from first call to <Stopwatch/> and <ManualEntry/> mocks
 *      Calls update handlers with provided inputs for times
 *      Calls userEvent.type for note
*/
async function setSleepInputs({
    stopwatchTime,
    startDate,
    endDate,
    note,
} : {
    stopwatchTime?: string;
    startDate?: Date;
    endDate?: Date;
    note?: string;
}) {
    // read parameters to first call of Stopwatch
    const {
        onTimeUpdate,
    } = (Stopwatch as jest.Mock).mock.calls[0][0];

    // read parameters to first call of ManualEntry
    const {
        onDatesUpdate,
    } = (ManualEntry as jest.Mock).mock.calls[0][0];

    // call update handlers for times
    if (stopwatchTime) {
        await act(() => onTimeUpdate?.(stopwatchTime));
    }
    if (startDate && endDate) {
        await act(() => onDatesUpdate?.(startDate, endDate));
    }

    // type into <TextInput/> component for note
    if (note) {
        await userEvent.type(
            screen.getByTestId("sleep-note-entry"),
            note
        );
    }
}


describe("Track sleep screen", () => {
    beforeEach(() => {
        // to clear the .mock.calls array
        (Alert.alert as jest.Mock).mockClear();
        jest.spyOn(console, "error").mockClear();
        (Stopwatch as jest.Mock).mockClear();
        (ManualEntry as jest.Mock).mockClear();
        (saveLog as jest.Mock).mockClear();
        (router.dismissTo as jest.Mock).mockClear();
    });

    test("Renders sleep tracking inputs", () => {
        render(<Sleep/>);

        expect(screen.getByTestId("sleep-stopwatch")).toBeTruthy();
        expect(screen.getByTestId("sleep-manual-time-entry")).toBeTruthy();
        expect(screen.getByTestId("sleep-note-entry")).toBeTruthy();
    });

    test("Renders form control buttons", () => {
        render(<Sleep/>);

        expect(screen.getByTestId("sleep-save-log-button")).toBeTruthy();
        expect(screen.getByTestId("sleep-reset-form-button")).toBeTruthy();
    });

    test("Catch unfilled inputs", async () => {
        render(<Sleep/>);
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // error message generated by handleSaveSleepLog()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe("Missing Information");
        expect((Alert.alert as jest.Mock).mock.calls[0][1])
            .toBe("Failed to save the Sleep log. Please provide either a stopwatch time or valid manual start and end times.");
    });

    test("Catch invalid time inputs", async () => {
        const testStart = new(Date);
        render(<Sleep/>);
        
        await setSleepInputs({ startDate: testStart, endDate: testStart });
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // error message generated by handleSaveSleepLog()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe("Missing Information");
        expect((Alert.alert as jest.Mock).mock.calls[0][1])
            .toBe("Failed to save the Sleep log. Please provide either a stopwatch time or valid manual start and end times.");
    });
            
    test("Refreshes on reset", async () => {
        const testNote = "test note";
        render(<Sleep/>);

        // write something in the note entry...
        await setSleepInputs({ note: testNote });
        expect(screen.getByDisplayValue(testNote)).toBeTruthy();  // ensure the typed note can be found

        const stopwatch = screen.getByTestId("sleep-stopwatch");  // get the displayed <Stopwatch/>
        const manualEntry = screen.getByTestId("sleep-manual-time-entry");  // get the displayed <ManualEntry/>

        await userEvent.press(
            screen.getByTestId("sleep-reset-form-button")
        );

        // ensure note is no longer present
        expect(() => screen.getByDisplayValue(testNote)).toThrow();
        // ensure new instance of <Stopwatch/> is being used
        expect(screen.getByTestId("sleep-stopwatch") === stopwatch).toBeFalsy();
        // ensure new instance of <ManualEntry/> is being used
        expect(screen.getByTestId("sleep-manual-time-entry") === manualEntry).toBeFalsy();
    });
    
    test("Catch saveLog() error", async () => {
        const testErrorMessage = "test error";

        // library/log-functions.ts -> saveLog() should be mocked to return:
        // { success: /* falsy value */, error: /* string */ }
        // This should cause error handling in app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        (saveLog as jest.Mock).mockImplementationOnce(
            async () => ({ success: false, error: testErrorMessage })
        );

        render(<Sleep/>);
        await setSleepInputs({stopwatchTime: "1:00:00"});  // set minimum required inputs
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // error message generated by library/log-functions.ts -> saveLog()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Failed to save sleep log: ${testErrorMessage}`);
    });

    test("Successfully saved sleep log", async () => {
        render(<Sleep/>);
        await setSleepInputs({stopwatchTime: "1:00:00"});  // set minimum required inputs
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe("Sleep log saved successfully!");

        // confirm that the expo-router was called to send the user back to the tracker page
        expect((router.dismissTo as jest.Mock)).toHaveBeenCalledTimes(1);
        expect((router.dismissTo as jest.Mock)).toHaveBeenLastCalledWith("/(tabs)");
    });

    test("Saves correct values (stopwatch)", async () => {
        const testNote = "test note";
        const testDurationMS = 1.111 * (60 * 60 * 1000);  // convert test duration (1.111 hours) to milliseconds
        const testDuration = (new Date(testDurationMS)).toISOString().substring(11, 19);  // convert ms to "hh:mm:ss"

        render(<Sleep/>);
        // set both stopwatch time and manual start/end times. Stopwatch time should take priority for saving
        await setSleepInputs({
            stopwatchTime: testDuration,
            startDate: new Date(),
            endDate: new Date(),
            note: testNote,
        });
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // get approximate time that the test was executed
        const executionTime = new Date();

        const savedValues = (saveLog as jest.Mock).mock.calls[0][0].fields;

        // Ensure saveLog() was called with the correct values
        const findfield = (name: string, value?: any) =>
            (field: field) => field.dbFieldName === name && (!value || field.value === value);
        const savedEndMS = savedValues.find(findfield("end_time")).value.getTime();  // should be the time at which the log was saved
        const savedStartMS = savedValues.find(findfield("start_time")).value.getTime();  // should be the log save time minus the duration
        
        expect(savedStartMS).toBeCloseTo(executionTime.getTime() - testDurationMS, -3.3);  // times are within ~1000 ms of each other
        expect(savedEndMS).toBeCloseTo(executionTime.getTime(), -3.3);  // times are within ~1000 ms of each other
        expect(savedValues.find(findfield("duration", testDuration))).toBeTruthy();
        expect(savedValues.find(findfield("note", testNote))).toBeTruthy();

        // Ensure that log was saved successfully
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe("Sleep log saved successfully!");
    });

    test("Saves correct values (manual time)", async () => {
        const testNote = "test note";
        const testManualDuration = 1.111 * (60 * 60 * 1000);  // convert test duration (1.111 hours) to milliseconds
        const testDurationStr = (new Date(testManualDuration)).toISOString().substring(11, 19);  // convert ms to hh:mm:ss
        const testStart = new Date();
        const testEnd = new Date(testStart.getTime() + testManualDuration);

        render(<Sleep/>);
        await setSleepInputs({
            startDate: testStart,
            endDate: testEnd,
            note: testNote,
        });
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        const savedValues = (saveLog as jest.Mock).mock.calls[0][0].fields;

        // Ensure saveLog() was called with the correct values
        const findfield = (name: string, value?: any) =>
            (field: field) => field.dbFieldName === name && (!value || field.value === value);
        expect(savedValues.find(findfield("start_time", testStart))).toBeTruthy();
        expect(savedValues.find(findfield("end_time", testEnd))).toBeTruthy();
        expect(savedValues.find(findfield("duration", testDurationStr))).toBeTruthy();
        expect(savedValues.find(findfield("note", testNote))).toBeTruthy();

        // Ensure that log was saved successfully
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe("Sleep log saved successfully!");
    });
});
