import { render, screen, userEvent } from "@testing-library/react-native";
import Sleep from "@/app/(trackers)/sleep";
import { Alert } from "react-native";
import supabase from "@/library/supabase-client";

jest.mock("expo-router", () => ({
    router: {
        replace: jest.fn(),
    },
}));

jest.mock("@/library/supabase-client", () => ({
    auth: {
        getUser: jest.fn(async () => ({ data: { user: null } }))
    },
    from: jest.fn(async () => null)//() => { })
}));

jest.mock("@/library/crypto", () =>({
    encryptData: async () => ""
}));

jest.mock("react-native", () => {
    const module = jest.requireActual("react-native");
    module.Alert.alert = jest.fn();
    return module;
});


describe("Track sleep screen", () => {
    test("Renders sleep tracking inputs", () => {
        render(<Sleep/>);

        expect(screen.getByTestId("sleep-stopwatch")).toBeTruthy();
        expect(screen.getByTestId("sleep-manual-time-entry")).toBeTruthy();
        expect(screen.getByTestId("sleep-note-entry")).toBeTruthy();
    });

    test("Renders form control buttons", () => {
        render(<Sleep/>);

        expect(screen.getByTestId("sleep-save-log-button")).toBeTruthy();
        expect(screen.getByTestId("sleep-reset-form-button")).toBeTruthy();
    });

    test("Catch invalid user", async () => {
        // supabase.auth.getUser() should be mocked to return:
        // { data: { user: null } }
        // This should cause error handling in app/library/utils.ts -> getActiveChildId()

        render(<Sleep/>);
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // error message generated by app/library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> saveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls.at(-2)[0]).toBe("Error: No authenticated user found");

        // error message generated by app/library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls.at(-1)[0]).toBe("Failed to save sleep log: No authenticated user found");
    });

    test("Catch no active child", async () => {
        // supabase.auth.getUser() should be mocked to return:
        // { data: { user: { user_metadata: {} } } }
        // This should cause error handling in app/library/utils.ts -> getActiveChildId()
        (supabase.auth.getUser as jest.Mock).mockImplementationOnce(
            async () => ({ data: { user: { user_metadata: {} } } })
        );

        render(<Sleep/>);
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // error message generated by app/library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> saveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls.at(-2)[0]).toBe("Error: No active child set in user metadata");

        // error message generated by app/library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls.at(-1)[0]).toBe("Failed to save sleep log: No active child set in user metadata");
    });

    test("Catch supabase select error", async () => {
        const testErrorMessage = "testErrorSelect";

        // supabase.auth.getUser() should be mocked to return:
        // { data: { user: { user_metadata: { activeChild: /* truthy value */ } } } }
        // This should cause error handling in app/library/utils.ts -> getActiveChildId()
        (supabase.auth.getUser as jest.Mock).mockImplementationOnce(
            async () => ({ data: { user: { user_metadata: { activeChild: true } } } })
        );

        // supabase.from().select().eq().eq().single() should be mocked to return:
        // { error: /* truthy value */ }
        // This should cause error handling in app/library/utils.ts -> getActiveChildId()
        (supabase.from as jest.Mock).mockImplementationOnce(
            () => ({
                select: () => ({
                    eq: () => ({
                        eq: () => ({
                            single: () => ({ error: testErrorMessage })
                        })
                    })
                })
            })
        );

        jest.spyOn(console, "error").mockImplementation(() => null);  // suppress console warnings from within the tested code

        render(<Sleep/>);
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // error message generated by app/library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> saveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls.at(-2)[0]).toBe(`Error: ${testErrorMessage}`);

        // error message generated by app/library/utils.ts -> getActiveChildId()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls.at(-1)[0]).toBe(`Failed to save sleep log: ${testErrorMessage}`);
    });

    test("Catch supabase insert error", async () => {
        const testErrorMessage = "testErrorInsert";

        // supabase.auth.getUser() should be mocked to return:
        // { data: { user: { user_metadata: { activeChild: /* truthy value */ } } } }
        // This should cause error handling in app/library/utils.ts -> getActiveChildId()
        (supabase.auth.getUser as jest.Mock).mockImplementation(
            async () => ({ data: { user: { user_metadata: { activeChild: true } } } })
        );

        // supabase.from().select().eq().eq().single() should be mocked to return:
        // { error: /* falsy value */ }
        // This should cause error handling in app/library/utils.ts -> getActiveChildId()
        (supabase.from as jest.Mock).mockImplementationOnce(
            () => ({
                select: () => ({
                    eq: () => ({
                        eq: () => ({
                            single: () => ({ data: {} })
                        })
                    })
                })
            })
        ).mockImplementationOnce(
            () => ({ insert: () => ({ error: testErrorMessage }) })
        )

        jest.spyOn(console, "error").mockImplementation(() => null);  // suppress console warnings from within the tested code

        render(<Sleep/>);
        await userEvent.press(
            screen.getByTestId("sleep-save-log-button")
        );

        // error message generated by supabase.from().insert() in app/(trackers)/sleep.tsx -> createSleepLog()
        // Alert.alert() called by app/(trackers)/sleep.tsx -> handleSaveSleepLog()
        expect((Alert.alert as jest.Mock).mock.calls.at(-1)[0]).toBe(`Failed to save sleep log: ${testErrorMessage}`);
    });
});
