import { render, screen, userEvent } from "@testing-library/react-native";
import GuestScreen from "@/app/(auth)/guest";
import { router } from 'expo-router';
import { useAuth } from '@/library/auth-provider';
import { Alert } from "react-native";

jest.mock("@/library/auth-provider", () => {
    const enterGuest = jest.fn();
    return {
        useAuth: () => ({
            enterGuest: enterGuest,
        }),
    };
});

jest.mock("expo-router", () => ({
    router: {
        replace: jest.fn(),
        back: jest.fn(),
    },
}));

jest.mock("react-native", () => {
    const module = jest.requireActual("react-native");
    module.Alert.alert = jest.fn();
    return module;
});


describe("Log in screen", () => {
    beforeEach(() => {
        // to clear the .mock.calls array
        (router.replace as jest.Mock).mockClear();
        (router.back as jest.Mock).mockClear();
        (Alert.alert as jest.Mock).mockClear();
        (useAuth().enterGuest as jest.Mock).mockClear();
    });

    test("Render nav buttons and info", () => {
        render(<GuestScreen/>);
      
        expect(screen.getByTestId("guest-info")).toBeTruthy();
        expect(screen.getByTestId("guest-cancel-button")).toBeTruthy();
        expect(screen.getByTestId("guest-continue-button")).toBeTruthy();
    });

    test("Redirects back on cancel", async () => {
        render(<GuestScreen/>);
      
        // press cancel button
        await userEvent.press(screen.getByTestId("guest-cancel-button"));

        // ensure user was sent back
        expect(router.back).toHaveBeenCalledTimes(1);
    });

    test("Catches enterGuest() error", async () => {
        const testErrorMessage = "test error";

        // library/auth-provider.tsx -> useAuth().enterGuest() should be mocked to throw an error
        // This should cause error handling in app/(auth)/signin.tsx -> handleSignIn()
        (useAuth().enterGuest as jest.Mock).mockImplementationOnce(
            async () => { throw new Error(testErrorMessage); }
        );

        render(<GuestScreen/>);
      
        // press continue button
        await userEvent.press(screen.getByTestId("guest-continue-button"));

        // error message generated by library/auth-provider.tsx -> useAuth().enterGuest()
        // Alert.alert() called by app/(auth)/guest.tsx -> handleGuest()
        expect((Alert.alert as jest.Mock).mock.calls[0][0]).toBe(`Failed To Enter Guest Mode`);
        expect((Alert.alert as jest.Mock).mock.calls[0][1]).toBe(testErrorMessage);
    });

    test("Redirects on enterGuest()", async () => {
        render(<GuestScreen/>);
      
        // press continue button
        await userEvent.press(screen.getByTestId("guest-continue-button"));

        expect((router.replace as jest.Mock).mock.calls[0][0]).toBe("/(tabs)");
        expect(useAuth().enterGuest as jest.Mock).toHaveBeenCalledTimes(1);
    });
});
